word_stats_french = {'trois' : '7',
'neuf' : '10',
'un' : '10',
'cinq' : '10',
'sept' : '12',
'deux' : '11',
'cinco' : '2',
'dos' : '6',
'tres' : '2',
'cuatro' : '3',
'siete' : '2',
'seis' : '2',
'nueve' : '3',
'un pijama' : '3',
'una camiseta' : '1',
'un chaqueta' : '1',
'unos pantalones' : '1',
'zapatos' : '1',
'quatre' : '7',
'huit' : '10',
'six' : '8',
'uno' : '1',
'ocho' : '1',
'la fresa' : '1',
'uva' : '3',
'el limon' : '3',
'la manzana' : '2',
'el platano' : '1',
'arandano' : '2',
'el tomate' : '2',
'la naranja' : '1',
'el melon' : '1'
}

french_highscore = '1600'

french_highest_streak = '9'